name: Docker Build, Push and Update k8s

on:
  push:
    tags:
      - '*'


jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run unit tests with coverage
      run: npm run test:cov

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage/lcov.info

  docker:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v5

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: viniciusfca/recriando-chatgpt:${{github.ref_name}}


  update-k8s:
    needs: docker
    runs-on: ubuntu-latest

    steps:
    - name: Checkout k8s repo
      uses: actions/checkout@v5
      with:
        repository: viniciusfca/gitops
        token: ${{ secrets.TOKEN_GITHUB }}

    - name: Update k8s deployment file
      run: |
        cd recriando-chatgpt
        ls
        sed -i 's|image: viniciusfca/recriando-chatgpt:.*|image: viniciusfca/recriando-chatgpt:${{github.ref_name}}|' Deployment.yaml

    - name: Commit and push changes
      run: |
        cd recriando-chatgpt
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add Deployment.yaml
        git commit -m "Update image version"
        git push origin main