name: Docker build, test and deploy

on:
  push:
    tags:
      - '*'

jobs:
 
  test:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup NodeJS
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Run unit tests
      run: npm run test:cov

  docker:
    name: Docker build and push
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
         username: ${{ secrets.DOCKERHUB_USERNAME }} 
         password: ${{ secrets.DOCKERHUB_PASSWORD }}
 
    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: viniciusfca/recriando-chatgpt:${{ github.ref_name }}

  update-k8s:
    runs-on: ubuntu-latest
    needs: docker

    steps:
    - name: Checkout gitops k8s
      uses: actions/checkout@v4
      with:
        repository: viniciusfca/gitops
        token: ${{ secrets.TOKEN_GITHUB }}
        
    - name: Update k8s deployment file
      run: |
        cd recriando-chatgpt
        ls   # lista arquivos (debug)
        sed -i 's|image: viniciusfca/recriando-chatgpt:.*|image: viniciusfca/recriando-chatgpt:${{github.ref_name}}|' Deployment.yaml
        # substitui a imagem antiga pela nova versão no Deployment.yaml    

    - name: Commit and push
      run: |
        cd recriando-chatgpt
        git config user.name "GitHub Actions"   # configura autor do commit
        git config user.email "actions@github.com"
        git add Deployment.yaml   # adiciona arquivo modificado
        git commit -m "Update image version"   # cria commit
        git push origin main   # envia alterações para branch main    
          

